"""add_gmail_fields

Revision ID: c1a7e3f6356e
Revises: 37d4ac4cca94
Create Date: 2026-01-29 18:21:40.146998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1a7e3f6356e'
down_revision: Union[str, None] = '37d4ac4cca94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gmail_refresh_token_encrypted', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('gmail_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('gmail_sync_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('gmail_last_sync_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gmail_last_sync_at')
    op.drop_column('users', 'gmail_sync_enabled')
    op.drop_column('users', 'gmail_token_expires_at')
    op.drop_column('users', 'gmail_refresh_token_encrypted')
    # ### end Alembic commands ###
