"""create_pending_applications

Revision ID: 706b6d524fa6
Revises: c1a7e3f6356e
Create Date: 2026-01-29 18:25:31.641808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '706b6d524fa6'
down_revision: Union[str, None] = 'c1a7e3f6356e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_applications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email_id', sa.String(length=255), nullable=False),
    sa.Column('email_subject', sa.String(length=500), nullable=False),
    sa.Column('email_snippet', sa.String(length=1000), nullable=True),
    sa.Column('email_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('parsed_company', sa.String(length=255), nullable=True),
    sa.Column('parsed_role', sa.String(length=255), nullable=True),
    sa.Column('parsed_status', sa.String(length=50), nullable=True),
    sa.Column('parsed_job_url', sa.String(length=2000), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_applications_email_id'), 'pending_applications', ['email_id'], unique=True)
    op.create_index(op.f('ix_pending_applications_status'), 'pending_applications', ['status'], unique=False)
    op.create_index(op.f('ix_pending_applications_user_id'), 'pending_applications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pending_applications_user_id'), table_name='pending_applications')
    op.drop_index(op.f('ix_pending_applications_status'), table_name='pending_applications')
    op.drop_index(op.f('ix_pending_applications_email_id'), table_name='pending_applications')
    op.drop_table('pending_applications')
    # ### end Alembic commands ###
