"""add_email_from

Revision ID: b61a59e0aa6b
Revises: 20260201_fulltext
Create Date: 2026-02-04 23:36:43.678215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b61a59e0aa6b'
down_revision: Union[str, None] = '20260201_fulltext'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_applications_applied_date', table_name='applications', postgresql_where='(deleted_at IS NULL)')
    op.drop_index('idx_applications_search_vector', table_name='applications', postgresql_using='gin')
    op.drop_index('idx_applications_status', table_name='applications', postgresql_where='(deleted_at IS NULL)')
    op.drop_column('applications', 'search_vector')
    op.add_column('pending_applications', sa.Column('email_from', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pending_applications', 'email_from')
    op.add_column('applications', sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed('((setweight(to_tsvector(\'english\'::regconfig, (COALESCE(company_name, \'\'::character varying))::text), \'A\'::"char") || setweight(to_tsvector(\'english\'::regconfig, (COALESCE(role_title, \'\'::character varying))::text), \'B\'::"char")) || setweight(to_tsvector(\'english\'::regconfig, (COALESCE(location, \'\'::character varying))::text), \'C\'::"char"))', persisted=True), autoincrement=False, nullable=True))
    op.create_index('idx_applications_status', 'applications', ['status'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index('idx_applications_search_vector', 'applications', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('idx_applications_applied_date', 'applications', [sa.text('applied_date DESC')], unique=False, postgresql_where='(deleted_at IS NULL)')
    # ### end Alembic commands ###
