"""add_digest_leads

Revision ID: 834aab695e36
Revises: d207dc09b637
Create Date: 2026-03-02 15:15:55.623654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '834aab695e36'
down_revision: Union[str, None] = 'd207dc09b637'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('stipend', sa.String(length=100), nullable=True))
    op.add_column('leads', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('leads', sa.Column('is_from_digest', sa.Boolean(), nullable=False, server_default='false'))
    op.drop_index('ix_leads_source_email_id', table_name='leads')
    op.create_index(op.f('ix_leads_source_email_id'), 'leads', ['source_email_id'], unique=False)
    op.create_unique_constraint('uq_lead_email_company_role', 'leads', ['source_email_id', 'company', 'role'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_lead_email_company_role', 'leads', type_='unique')
    op.drop_index(op.f('ix_leads_source_email_id'), table_name='leads')
    op.create_index('ix_leads_source_email_id', 'leads', ['source_email_id'], unique=True)
    op.drop_column('leads', 'is_from_digest')
    op.drop_column('leads', 'location')
    op.drop_column('leads', 'stipend')
    # ### end Alembic commands ###
